-- seed.sql — concessionárias (mesma lista de js/seed.js, que espelha
-- hd_oferta_concessionaria do titan-helpdesk — seção 12.2 do plano).
-- Mantenha esta lista sincronizada manualmente com CONCESSIONARIAS em js/seed.js.

insert into public.concessionaria (codigo, nome, uf, aliases) values
('CPFL-PAULISTA', 'CPFL Paulista', 'SP', array['CPFL','CPFL PAULISTA','COMPANHIA PAULISTA DE FORCA E LUZ']),
('CPFL-PIRATININGA', 'CPFL Piratininga', 'SP', array['CPFL PIRATININGA','COMPANHIA PIRATININGA DE FORCA E LUZ']),
('CPFL-SANTA-CRUZ', 'CPFL Santa Cruz', 'SP', array['CPFL SANTA CRUZ','COMPANHIA LUZ E FORCA SANTA CRUZ']),
('RGE', 'RGE Sul', 'RS', array['RGE','RGE SUL','RIO GRANDE ENERGIA']),
('CEMIG-D', 'CEMIG Distribuição', 'MG', array['CEMIG','CEMIG-D','CEMIG D','CEMIG DISTRIBUICAO']),
('COPEL-DIS', 'Copel Distribuição', 'PR', array['COPEL','COPEL-DIS','COPEL DIS','COPEL DISTRIBUICAO']),
('CELESC-DIS', 'Celesc Distribuição', 'SC', array['CELESC','CELESC-DIS','CELESC DIS','CELESC DISTRIBUICAO']),
('LIGHT', 'Light SESA', 'RJ', array['LIGHT','LIGHT SESA','LIGHT SERVICOS DE ELETRICIDADE']),
('ENEL-SP', 'Enel Distribuição São Paulo', 'SP', array['ENEL SP','ENEL-SP','ELETROPAULO','ENEL DISTRIBUICAO SAO PAULO']),
('ENEL-RJ', 'Enel Distribuição Rio', 'RJ', array['ENEL RJ','ENEL-RJ','AMPLA','ENEL DISTRIBUICAO RIO']),
('ENEL-CE', 'Enel Distribuição Ceará', 'CE', array['ENEL CE','ENEL-CE','COELCE','ENEL DISTRIBUICAO CEARA']),
('ENEL-GO', 'Enel Distribuição Goiás', 'GO', array['ENEL GO','ENEL-GO','CELG','CELG-D','ENEL DISTRIBUICAO GOIAS','EQUATORIAL GO']),
('ELEKTRO', 'Neoenergia Elektro', 'SP', array['ELEKTRO','NEOENERGIA ELEKTRO']),
('COELBA', 'Neoenergia Coelba', 'BA', array['COELBA','NEOENERGIA COELBA','NEOENERGIA BA']),
('CELPE', 'Neoenergia Pernambuco', 'PE', array['CELPE','NEOENERGIA PE','NEOENERGIA PERNAMBUCO']),
('COSERN', 'Neoenergia Cosern', 'RN', array['COSERN','NEOENERGIA RN','NEOENERGIA COSERN']),
('CEB-DIS', 'Neoenergia Brasília', 'DF', array['CEB','CEB-DIS','NEOENERGIA BRASILIA','NEOENERGIA DF']),
('EDP-SP', 'EDP São Paulo', 'SP', array['EDP SP','EDP-SP','BANDEIRANTE','EDP SAO PAULO']),
('EDP-ES', 'EDP Espírito Santo', 'ES', array['EDP ES','EDP-ES','ESCELSA','EDP ESPIRITO SANTO']),
('ENERGISA-MT', 'Energisa Mato Grosso', 'MT', array['ENERGISA MT','CEMAT','ENERGISA MATO GROSSO']),
('ENERGISA-MS', 'Energisa Mato Grosso do Sul', 'MS', array['ENERGISA MS','ENERSUL','ENERGISA MATO GROSSO DO SUL']),
('ENERGISA-PB', 'Energisa Paraíba', 'PB', array['ENERGISA PB','SAELPA','ENERGISA PARAIBA']),
('ENERGISA-SE', 'Energisa Sergipe', 'SE', array['ENERGISA SE','ENERGIPE','ENERGISA SERGIPE']),
('ENERGISA-MG', 'Energisa Minas Gerais', 'MG', array['ENERGISA MG','ENERGISA MINAS GERAIS']),
('ENERGISA-TO', 'Energisa Tocantins', 'TO', array['ENERGISA TO','CELTINS','ENERGISA TOCANTINS']),
('ENERGISA-SS', 'Energisa Sul-Sudeste', 'SP', array['ENERGISA SUL-SUDESTE','ENERGISA SUL SUDESTE','CAIUA']),
('ENERGISA-RO', 'Energisa Rondônia', 'RO', array['ENERGISA RO','CERON','ENERGISA RONDONIA']),
('ENERGISA-AC', 'Energisa Acre', 'AC', array['ENERGISA AC','ELETROACRE','ENERGISA ACRE']),
('ENERGISA-NF', 'Energisa Nova Friburgo', 'RJ', array['ENERGISA NOVA FRIBURGO','CENF']),
('EQUATORIAL-PA', 'Equatorial Pará', 'PA', array['EQUATORIAL PA','CELPA','EQUATORIAL PARA']),
('EQUATORIAL-MA', 'Equatorial Maranhão', 'MA', array['EQUATORIAL MA','CEMAR','EQUATORIAL MARANHAO']),
('EQUATORIAL-PI', 'Equatorial Piauí', 'PI', array['EQUATORIAL PI','CEPISA','EQUATORIAL PIAUI']),
('EQUATORIAL-AL', 'Equatorial Alagoas', 'AL', array['EQUATORIAL AL','CEAL','EQUATORIAL ALAGOAS']),
('EQUATORIAL-RS', 'Equatorial CEEE', 'RS', array['CEEE','CEEE-D','EQUATORIAL RS','EQUATORIAL CEEE']),
('EQUATORIAL-AP', 'Equatorial Amapá', 'AP', array['CEA','EQUATORIAL AP','EQUATORIAL AMAPA']),
('AME', 'Amazonas Energia', 'AM', array['AMAZONAS ENERGIA','AME','CEAM']),
('RORAIMA', 'Roraima Energia', 'RR', array['RORAIMA ENERGIA','BOA VISTA ENERGIA']),
('SULGIPE', 'Sulgipe', 'SE', array['SULGIPE','CIA SUL SERGIPANA DE ELETRICIDADE']),
('COCEL', 'Cocel', 'PR', array['COCEL','COMPANHIA CAMPOLARGUENSE DE ENERGIA']),
('FORCEL', 'Forcel', 'PR', array['FORCEL','FORCA E LUZ CORONEL VIVIDA']),
('DMED', 'DMED', 'MG', array['DMED','DME DISTRIBUICAO']),
('MUX', 'MUX Energia', 'RS', array['MUX','MUX ENERGIA','MUXFELDT MARIN']),
('EFLUL', 'EFLUL', 'SC', array['EFLUL','EMPRESA FORCA E LUZ URUSSANGA']),
('HIDROPAN', 'Hidropan', 'RS', array['HIDROPAN']),
('CERR', 'CERR', 'RR', array['CERR']),
('OUTRA', 'Outra / não identificada', null, array[]::text[])
on conflict (codigo) do update set nome = excluded.nome, uf = excluded.uf, aliases = excluded.aliases;
